data <- read.table(file = "household_power_consumption.txt", sep = ";", header = TRUE, stringsAsFactors = FALSE, na.strings = "?")
data$Date = as.Date(data$Date, "%d/%m/%Y")
mydata <- data
k1 <- as.Date("2007-02-01")
k2 <- as.Date("2007-02-02")
data <- data[which(data[,1] == k1),]
mydata <- mydata[which(mydata[,1] == k2),]
data <- rbind(data, mydata)
case <- data
datetime <- strptime(paste(data$Date, data$Time), format = "%Y-%m-%d %H:%M:%S")
case <- cbind(case, datetime)
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow = c(2,2), mar = c(4,4,4,2), oma = c(1,1,0,0))
plot(case$datetime, case$Global_active_power, type = "n", ylab = "Global Active Power", xlab = " ")
lines(case$datetime, case$Global_active_power, pch = ".", type = "o")
plot(case$datetime, case$Voltage, type = "n", ylab = "Voltage", xlab = "datetime")
lines(case$datetime, case$Voltage, pch = ".", type = "o")
plot(case$datetime, case$Sub_metering_1, type = "n", ylab = "Energy sub metering", xlab = " ")
lines(case$datetime, case$Sub_metering_1, pch = ".", type = "o")
lines(case$datetime, case$Sub_metering_2, pch = ".", type = "o", col = "red")
lines(case$datetime, case$Sub_metering_3, pch = ".", type = "o", col = "blue")
legend("topright", lwd = 2, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), pt.cex = 2, cex = 1, bty = "n")
plot(case$datetime, case$Global_reactive_power, type = "n", ylab = "Global_reactive_power", xlab = "datetime")
lines(case$datetime, case$Global_reactive_power, pch = ".", type = "o")
dev.off()
